/* This file is part of NetBioDyn.
 *
 *   NetBioDyn is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 3 of the License, or
 *   any later version.
 *
 *   NetBioDyn is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with NetBioDyn; if not, write to the Free Software
 *   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */

/*
 * WndEditEnvironnement.java
 *
 * Created on 18 novembre 2007, 13:26
 */
package netbiodyn.ihm;

import netbiodyn.util.UtilFileFilter;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import netbiodyn.util.Lang;
import netbiodyn.util.UtilDivers;

/**
 *
 * @author ballet
 */
public class WndEditEnvironnement extends javax.swing.JDialog {

     private Env_Parameters parameters;
    private String DialogResult = new String("");

    public WndEditEnvironnement(Env_Parameters parameters) {
        this.parameters = parameters;
        this.setModal(true);
        initComponents();
        this.WndCliEditEnvironnement_Load();
    }

    public void WndCliEditEnvironnement_Load() {
        // Language
        if (Lang.getInstance().getLang().equals("FR")) {
            jLabelEnv.setText("Environnement");
            jLabelX.setText("Taille X");
            jLabelY.setText("Taille Y");
            jLabelZ.setText("Taille Z");
            button_enlever_image_deco.setText("Pas d'image");
            button_annuler.setText("Annuler");
        } else {
            jLabelEnv.setText("Environment");
            jLabelX.setText("Size X");
            jLabelY.setText("Size Y");
            jLabelZ.setText("Size Z");
            button_enlever_image_deco.setText("No image");
            button_annuler.setText("Cancel");
        }

        textBox_tailleX.setText(((Integer) (parameters.getX())).toString());
        textBox_tailleY.setText(((Integer) (parameters.getY())).toString());
        textBox_tailleZ.setText(((Integer) (parameters.getZ())).toString());
        richTextBox_description.setText(parameters.getDescription());
    }
    
     public String getDialogResult() {
        return DialogResult;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEnv = new javax.swing.JLabel();
        button_annuler = new javax.swing.JButton();
        jLabelX = new javax.swing.JLabel();
        textBox_tailleX = new javax.swing.JTextField();
        jLabelY = new javax.swing.JLabel();
        textBox_tailleY = new javax.swing.JTextField();
        button_image_deco = new javax.swing.JToggleButton();
        button_enlever_image_deco = new javax.swing.JToggleButton();
        button_OK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        richTextBox_description = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabelZ = new javax.swing.JLabel();
        textBox_tailleZ = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(null);

        jLabelEnv.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabelEnv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEnv.setText("Environnement");
        getContentPane().add(jLabelEnv);
        jLabelEnv.setBounds(134, 0, 230, 29);

        button_annuler.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        button_annuler.setText("Annuler");
        button_annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_annulerMouseClicked(evt);
            }
        });
        getContentPane().add(button_annuler);
        button_annuler.setBounds(10, 250, 150, 23);

        jLabelX.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabelX.setText("Taille X");
        getContentPane().add(jLabelX);
        jLabelX.setBounds(10, 47, 34, 15);

        textBox_tailleX.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        textBox_tailleX.setText("100");
        getContentPane().add(textBox_tailleX);
        textBox_tailleX.setBounds(70, 40, 70, 21);

        jLabelY.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabelY.setText("Taille Y");
        getContentPane().add(jLabelY);
        jLabelY.setBounds(160, 47, 35, 15);

        textBox_tailleY.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        textBox_tailleY.setText("100");
        getContentPane().add(textBox_tailleY);
        textBox_tailleY.setBounds(210, 40, 80, 21);

        button_image_deco.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        button_image_deco.setText("Image");
        button_image_deco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_image_decoMouseClicked(evt);
            }
        });
        getContentPane().add(button_image_deco);
        button_image_deco.setBounds(90, 90, 110, 30);

        button_enlever_image_deco.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        button_enlever_image_deco.setText("Pas d'image");
        button_enlever_image_deco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_enlever_image_decoMouseClicked(evt);
            }
        });
        getContentPane().add(button_enlever_image_deco);
        button_enlever_image_deco.setBounds(220, 90, 120, 30);

        button_OK.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        button_OK.setText("OK");
        button_OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_OKMouseClicked(evt);
            }
        });
        button_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_OKActionPerformed(evt);
            }
        });
        getContentPane().add(button_OK);
        button_OK.setBounds(160, 250, 300, 23);

        richTextBox_description.setColumns(20);
        richTextBox_description.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        richTextBox_description.setRows(5);
        jScrollPane1.setViewportView(richTextBox_description);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 450, 90);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel4.setText("Description");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 54, 15);

        jLabelZ.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabelZ.setText("Taille Z");
        getContentPane().add(jLabelZ);
        jLabelZ.setBounds(330, 47, 34, 15);

        textBox_tailleZ.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        textBox_tailleZ.setText("1");
        getContentPane().add(textBox_tailleZ);
        textBox_tailleZ.setBounds(380, 40, 80, 21);

        jLabel6.setBackground(new java.awt.Color(153, 153, 255));
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 490, 30);

        setSize(new java.awt.Dimension(491, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_annulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_annulerMouseClicked
        // TODO add your handling code here:
        DialogResult = new String("Cancel");
        setVisible(false);
    }//GEN-LAST:event_button_annulerMouseClicked

    private void button_image_decoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_image_decoMouseClicked
        // TODO add your handling code here:
        // Placement de l'image dans le fond de la pictbox
        JFileChooser openFileDialog1 = new JFileChooser();
        UtilFileFilter filtre = new UtilFileFilter("Images", "bmp", "gif", "jpeg", "jpg", "png");
        openFileDialog1.setFileFilter(filtre);
        openFileDialog1.setDialogTitle("Image");
        //openFileDialog1.setSelectedFile(new File(_env._str_image_deco));
        int returnval = openFileDialog1.showOpenDialog(this);
        if (returnval == JFileChooser.APPROVE_OPTION) {
            String fileName = openFileDialog1.getCurrentDirectory().getAbsolutePath() + File.separatorChar + openFileDialog1.getSelectedFile().getName();
            if (!fileName.startsWith("http") && !fileName.startsWith("file")) {
                if (fileName.startsWith("/")) {
                    fileName = "file://" + fileName; // Linux
                } else {
                    fileName = "file:///" + fileName; // Windows
                }
            }

            BufferedImage img = null;
            try {
                img = ImageIO.read(new URL(fileName));
                //File F = new File(fileName);
                String nom_F = UtilDivers.fichier(fileName); //F.getName();                
                // Flip selon x
                for (int x = 0; x < img.getWidth(); x++) {
                    for (int y = 0; y < img.getHeight() / 2; y++) {
                        int co1 = img.getRGB(x, y);
                        int co2 = img.getRGB(x, img.getHeight() - y - 1);
                        img.setRGB(x, y, co2);
                        img.setRGB(x, img.getHeight() - y - 1, co1);
                    }
                }
                parameters.setImage(img);
                parameters.setStr_image_deco(nom_F); //Path.GetFileName(openFileDialog1.FileName);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
            //_env.pictureBox1.setIcon(img);

        }
    }//GEN-LAST:event_button_image_decoMouseClicked

    private void button_enlever_image_decoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_enlever_image_decoMouseClicked
        // TODO add your handling code here:
        parameters.setImage(null);
        parameters.setStr_image_deco(""); //Path.GetFileName(openFileDialog1.FileName);
    }//GEN-LAST:event_button_enlever_image_decoMouseClicked

    private void button_OKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_OKMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_button_OKMouseClicked

    private void button_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_OKActionPerformed
        // TODO add your handling code here:
        int new_tailleX = parameters.getX();
        int new_tailleY = parameters.getY();
        int new_tailleZ = parameters.getZ();
        try {
            new_tailleX = Integer.parseInt(textBox_tailleX.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        try {
            new_tailleY = Integer.parseInt(textBox_tailleY.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        try {
            new_tailleZ = Integer.parseInt(textBox_tailleZ.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

        // Redimensionnement effectif de l'environnement
        if (new_tailleX !=  parameters.getX() || new_tailleY !=  parameters.getY() || new_tailleZ !=  parameters.getZ()) {
            int res;
            if (parameters.getLang().equals("FR")) {
                res = JOptionPane.showConfirmDialog(this, "Redimensionner l'environnement enlèvera toutes les entités. Voulez-vous vraiment redimensionner l'environnement ?", "Attention", JOptionPane.INFORMATION_MESSAGE);
            } else {
                res = JOptionPane.showConfirmDialog(this, "Resizing the environnement will remove all entities. Do you want really to resize the environment?", "Attention", JOptionPane.INFORMATION_MESSAGE);
            }

            if (res == JOptionPane.YES_OPTION) {
                    parameters.setX(new_tailleX);
                    parameters.setY(new_tailleY);
                    parameters.setZ(new_tailleZ);          
                    parameters.setDescription(richTextBox_description.getText());
            }
        }       
        DialogResult = new String("OK");
        setVisible(false);
    }//GEN-LAST:event_button_OKActionPerformed

    public Env_Parameters getParameters() {
        return parameters;
    }

    public void setParameters(Env_Parameters parameters) {
        this.parameters = parameters;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_OK;
    private javax.swing.JButton button_annuler;
    private javax.swing.JToggleButton button_enlever_image_deco;
    private javax.swing.JToggleButton button_image_deco;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelEnv;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelY;
    private javax.swing.JLabel jLabelZ;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea richTextBox_description;
    private javax.swing.JTextField textBox_tailleX;
    private javax.swing.JTextField textBox_tailleY;
    private javax.swing.JTextField textBox_tailleZ;
    // End of variables declaration//GEN-END:variables

}
