/*
 * Moteur.java
 *
 * Created on 26 décembre 2007, 21:52
 */

package netbiodyn;

/**
 *
 * @author  user
 */
public class Moteur extends ProtoBioDyn {
    
    /** Creates new form Moteur */
    public Moteur() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
