/*
 * Entite.java
 *
 * Created on 11 decembre 2007, 15:46
 */
package netbiodyn;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JTextArea;

/**
 *
 * @author User
 */
public class ProtoSimplexel extends ProtoBioDyn {

    /**
     * Creates new form Entite
     */
    public ProtoSimplexel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        _description = new javax.swing.JTextArea();

        _description.setColumns(20);
        _description.setRows(5);
        jScrollPane2.setViewportView(_description);

        add(jScrollPane2);
        jScrollPane2.setBounds(118, 5, 74, 54);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public ArrayList<String> toSave() {
        ArrayList<String> toSave = super.toSave();
        toSave.add(new String("\tcouleur:").concat(((Integer) this.Couleur.getRGB()).toString()) + "\n");
        toSave.add(new String("\tdemie_vie:").concat(((Double) this.DemieVie).toString()) + "\n");
        toSave.add(new String("\tvidable:").concat(((Boolean) this.Vidable).toString()) + "\n");
        return toSave;
    }


    public double DemieVie = 0;
    public Color Couleur = Color.BLUE;
    public boolean Vidable = true;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextArea _description;
    public javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public JTextArea getDescription() {
        return _description;
    }

    
    
}
